config/routes.rb
Eventhero::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  match '/signup',      to: 'users#new'

  match '/signin',      to: 'sessions#new'
  match '/signout',     to: 'sessions#destroy'

  match '/contact',     to: 'static_pages#contact'
  match '/howitworks',  to: 'static_pages#howitworks'
  match '/about',       to: 'static_pages#about'
  match '/comingsoon',  to: 'static_pages#comingsoon'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
  					format: { with: VALID_EMAIL_REGEX },
  					uniqueness: { case_sensitive: false }


  validates :name, 	length: { maximum: 50 },
  					uniqueness: { case_sensitive: false }

  validates :password,					      length: { minimum: 6 }
  	
  validates :password_confirmation,		presence: true 

  before_save { |user| user.email = email.downcase }
  before_save { |user| user.name = user.email if user.name? == false }
  before_save :create_remember_token


  private

      def create_remember_token
        self.remember_token = SecureRandom.urlsafe_base64
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user= User.find_by_email(params[:session][:email]) 
		if user && user.authenticate(params[:session][:password])
			sign_in user 
			redirect_back_or user 
		else
			flash.now[:error] = 'Invalid email/password combination'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def howitworks
  end

  def about
  end

  def comingsoon
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :index]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :not_signed_in,  only: :new

  def index
  end

  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
    if signed_in?
      redirect_to(root_path)
    else
    	@user = User.new(params[:user])
    	if @user.save
        sign_in @user
        UserMailer.registration_confirmation(@user).deliver
    		flash[:success] = "Welcome to EventHero!"
    		redirect_to @user 
    	else
    		render 'new'
    	end
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user 
      redirect_to @user 
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "User destroyed"
    redirect_to users_path
  end


  private

        def signed_in_user
          unless signed_in?
            store_location
            redirect_to signin_path, notice: "Please sign in."
          end
        end

        def correct_user
          @user = User.find(params[:id])
          redirect_to(root_path) unless current_user?(@user)
        end

        def not_signed_in
          if signed_in?
            redirect_to(root_path)
          end
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		self.current_user = user 
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user 
	end

	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end

	def current_user?(user)
		user==current_user
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.fullpath
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	#return gravatar for user
	def gravatar_for(user, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Event Hero", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventhero | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>

</head>
<body>
	<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About Us") %>
<h1>About EventHero</h1>
<p>EventHero is for people who love creating and organizing events, but hate the tedious aspects of collecting money, getting everyone's input, and getting their guests to commit.  Eventhero solves this problem by creating a simple platform for Planning, Inviting, Getting Feedback, and Collecting Money.  Start planning with Eventhero today for guaranteed successful events.
</p>

app/views/static_pages/comingsoon.html.erb
<% provide(:title, "Coming Soon") %>
<h1>This Feature is being added, come back soon!</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact Us") %> 
<h1>Contact Us</h1>
<p>
	If you have any questions or you want to talk to the creator of EventHero, send me an <a href="mailto:scott.bold@gmail.com">email.</a>
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center hero-unit">
	<h1>Welcome to EventHero</h1>
	<h2>
		The easiest way for normal people to plan amazing events!
	</h2>
</div>

<div class="row">
	<div class="span8 offset2 center">
		<h2>
			Sign up to Create Your First Event!
		</h2>
	</div>
	<div class="row">
		<div class="span4 offset2 center">
			<%= link_to "Sign Up", signup_path, class: "btn btn-large btn-primary" %>
		</div>
		<div class="span4 center">
			<%= link_to "FB Sign Up", comingsoon_path, class: "btn btn-large btn-primary" %>
		</div>
	</div>
</div>

app/views/static_pages/howitworks.html.erb
<% provide(:title, "How It Works") %>
<h1>Here's how it works...</h1>
<p>Sign up, create event, send invites, get money, collaborate, success!</p>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>

			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
</div>